// Generates src/lib/abi.ts from Foundry artifacts so the app always matches the deployed contracts.
import { readFileSync, writeFileSync } from "node:fs";

const out = "../contracts/out";
const pick = (file: string, name: string) =>
  JSON.parse(readFileSync(`${out}/${file}/${name}.json`, "utf8")).abi;

const erc20 = [
  { type: "function", name: "balanceOf", stateMutability: "view", inputs: [{ name: "a", type: "address" }], outputs: [{ type: "uint256" }] },
  { type: "function", name: "allowance", stateMutability: "view", inputs: [{ name: "o", type: "address" }, { name: "s", type: "address" }], outputs: [{ type: "uint256" }] },
  { type: "function", name: "approve", stateMutability: "nonpayable", inputs: [{ name: "s", type: "address" }, { name: "v", type: "uint256" }], outputs: [{ type: "bool" }] },
];
const memo = [
  { type: "function", name: "memo", stateMutability: "nonpayable", inputs: [{ name: "target", type: "address" }, { name: "data", type: "bytes" }, { name: "memoId", type: "bytes32" }, { name: "memoData", type: "bytes" }], outputs: [] },
];

const body = [
  "// generated by scripts/abi.ts — do not edit",
  `export const collectiveAbi = ${JSON.stringify(pick("Collective.sol", "Collective"))} as const;`,
  `export const factoryAbi = ${JSON.stringify(pick("CollectiveFactory.sol", "CollectiveFactory"))} as const;`,
  `export const erc20Abi = ${JSON.stringify(erc20)} as const;`,
  `export const memoAbi = ${JSON.stringify(memo)} as const;`,
  "",
].join("\n");
writeFileSync("src/lib/abi.ts", body);
writeFileSync("src/lib/deployment.json", readFileSync("../deployments/arc-mainnet.json", "utf8"));
console.log("abi.ts written");
