import { defineStrings } from "../lib/i18n";

// Every user-facing string in the app, English + Turkish.
defineStrings({
  // brand + wallet
  tagline: ["the guild chest, onchain", "loncanın ortak kasası, zincirde"],
  "wallet.label": ["your wallet", "cüzdanın"],
  "wallet.pitch": ["Pin your wallet to the board to act. Looking around works without one.", "İşlem yapmak için cüzdanını panoya iğnele. Bakınmak için gerek yok."],
  "wallet.connect": ["Connect wallet", "Cüzdanı bağla"],
  "wallet.opening": ["Opening wallet…", "Cüzdan açılıyor…"],
  "wallet.unpin": ["Unpin", "Ayır"],
  "wallet.switch": ["Switch to Arc", "Arc ağına geç"],
  "wallet.needConnect": ["Connect your wallet to do this.", "Bunun için cüzdanını bağla."],

  // home
  "home.what": ["what this is", "bu ne"],
  "home.whatBody": [
    "One chest for a team that earns together. Every payment is pinned to the job that earned it, a reserve goes aside first, the rest is paid out by what each person did.",
    "Birlikte kazanan ekip için tek kasa. Her ödeme onu getiren işe iğnelenir, önce yedek ayrılır, kalanı herkesin yaptığı işe göre dağıtılır.",
  ],
  "home.yourChests": ["your chests", "kasaların"],
  "home.title": ["The board.", "Pano."],
  "home.open": ["Open a chest →", "Kasa aç →"],
  "home.connectFirst": ["Connect your wallet to see the chests you belong to.", "Üyesi olduğun kasaları görmek için cüzdanını bağla."],
  "home.empty": ["No chest on your board yet.", "Panonda henüz kasa yok."],
  "home.emptyHint": ["Open one for your team, or look at the live proof chest on the right.", "Ekibin için bir tane aç ya da sağdaki canlı örnek kasaya göz at."],
  "home.thisPeriod": ["USDC this period", "USDC bu dönem"],
  "home.live": ["live on Arc mainnet", "Arc mainnet'te canlı"],
  "home.proofBody": [
    "A real chest: a 0.10 USDC invoice paid through Arc Memo, reserve set aside, paid out by share.",
    "Gerçek bir kasa: 0,10 USDC'lik fatura Arc Memo üzerinden ödendi, yedek ayrıldı, paya göre dağıtıldı.",
  ],
  "home.lookInside": ["Look inside →", "İçine bak →"],
  "home.how": ["how it works", "nasıl çalışır"],
  "home.how1": ["Open a chest with your team's wallets.", "Ekibinin cüzdanlarıyla bir kasa aç."],
  "home.how2": ["Pin an invoice: who did the work, what share.", "Fatura iğnele: işi kim yaptı, payı ne."],
  "home.how3": ["Send the pay link; the client pays in USDC on Arc.", "Ödeme bağlantısını gönder; müşteri Arc'ta USDC ile öder."],
  "home.how4": ["Reserve fills first, the rest is shared at period end.", "Önce yedek dolar, kalanı dönem sonunda paylaşılır."],

  // new chest
  "new.cant": ["what can't happen", "ne olamaz"],
  "new.cant1": ["Nobody, not even you, can take money out alone.", "Kimse, sen bile, tek başına para çekemez."],
  "new.cant2": ["Rules change only when more than half of the members vote, after a waiting time.", "Kurallar ancak üyelerin yarısından fazlası oy verirse, bir bekleme süresinden sonra değişir."],
  "new.cant3": ["The reserve leaves only by vote.", "Yedek yalnızca oylamayla çıkar."],
  "new.label": ["new chest", "yeni kasa"],
  "new.title": ["Open a chest for your team.", "Ekibin için bir kasa aç."],
  "new.name": ["name", "isim"],
  "new.members": ["members", "üyeler"],
  "new.remove": ["Remove", "Çıkar"],
  "new.addMember": ["+ Add member", "+ Üye ekle"],
  "new.reserve": ["reserve", "yedek"],
  "new.reserveBody": ["A slice of every payment goes aside until the reserve is full.", "Yedek dolana kadar her ödemeden bir pay kenara ayrılır."],
  "new.reserveShare": ["share of each payment (%)", "her ödemeden ayrılan pay (%)"],
  "new.reserveTarget": ["fill up to (USDC)", "şu tutara kadar dolsun (USDC)"],
  "new.rhythm": ["payout rhythm", "dağıtım ritmi"],
  "new.rhythmBody": ["How often the pot is shared out, and how long a vote waits.", "Biriken tutar ne sıklıkla paylaşılır, oylamalar ne kadar bekler."],
  "new.every": ["pay out every", "şu sıklıkla dağıt"],
  "new.wait": ["votes wait", "oylamalar bekler"],
  "new.p1h": ["1 hour (try it out)", "1 saat (denemek için)"],
  "new.p1w": ["1 week", "1 hafta"],
  "new.p2w": ["2 weeks", "2 hafta"],
  "new.p1m": ["1 month", "1 ay"],
  "new.w1h": ["1 hour", "1 saat"],
  "new.w1d": ["1 day", "1 gün"],
  "new.w3d": ["3 days", "3 gün"],
  "new.agent": ["agent (optional)", "ajan (isteğe bağlı)"],
  "new.agentBody": [
    "An agent can match unlabelled income to a member and pay allowed bills, up to a limit each period. Anything above goes to a vote.",
    "Ajan, etiketsiz gelen parayı bir üyeye eşleştirebilir ve izin verilen faturaları ödeyebilir; her dönem bir sınıra kadar. Üstü oylamaya gider.",
  ],
  "new.agentAddr": ["agent address", "ajan adresi"],
  "new.agentAddrPh": ["0x… or leave empty", "0x… ya da boş bırak"],
  "new.agentCap": ["limit per period (USDC)", "dönem başı sınır (USDC)"],
  "new.pin": ["pin it", "iğnele"],
  "new.ready": ["Ready. Opening a chest costs about a cent of USDC in gas on Arc.", "Hazır. Arc'ta kasa açmak yaklaşık 1 sent USDC tutar."],
  "new.submit": ["Open the chest", "Kasayı aç"],
  "new.submitting": ["Opening…", "Açılıyor…"],
  "new.err.name": ["Give the chest a name.", "Kasaya bir isim ver."],
  "new.err.one": ["Add at least one member.", "En az bir üye ekle."],
  "new.err.max": ["At most 50 members.", "En fazla 50 üye."],
  "new.err.addr": ["Every member must be a wallet address (0x…).", "Her üye bir cüzdan adresi olmalı (0x…)."],
  "new.err.dup": ["A member is listed twice.", "Bir üye iki kez yazılmış."],
  "new.err.reserve": ["Reserve share must be between 0 and 100%.", "Yedek payı %0 ile %100 arasında olmalı."],
  "new.err.agent": ["Agent must be a wallet address or empty.", "Ajan bir cüzdan adresi olmalı ya da boş kalmalı."],
  "tx.openChest": ["Open chest", "Kasa açma"],

  // chest
  "chest.members": ["members", "üyeler"],
  "chest.you": ["you", "sen"],
  "chest.agent": ["agent", "ajan"],
  "chest.rules": ["rules", "kurallar"],
  "chest.rule1": ["{pct} of each payment to reserve, up to {target} USDC", "her ödemenin {pct}'i yedeğe, {target} USDC'ye kadar"],
  "chest.rule2": ["pay out every {d}", "her {d} dağıtım"],
  "chest.rule3": ["votes: more than half, then {d}", "oylama: yarıdan fazlası, sonra {d} bekleme"],
  "chest.rule4": ["agent limit {cap} USDC / period", "ajan sınırı dönem başı {cap} USDC"],
  "chest.label": ["chest", "kasa"],
  "chest.lookingIn": ["You're looking in. Only members can pin invoices or vote.", "Dışarıdan bakıyorsun. Fatura iğnelemek ve oy vermek yalnızca üyelere açık."],
  "chest.pot": ["this period's pot · #{n}", "bu dönem biriken · #{n}"],
  "chest.over": ["Period is over: ready to pay out.", "Dönem bitti: dağıtıma hazır."],
  "chest.paysIn": ["Pays out in {d}", "{d} sonra dağıtılır"],
  "chest.payOut": ["Pay out now", "Şimdi dağıt"],
  "chest.payingOut": ["Paying out…", "Dağıtılıyor…"],
  "chest.reserve": ["reserve", "yedek"],
  "chest.of": ["of {target} USDC", "/ {target} USDC"],
  "chest.onlyVote": ["Only a vote can release it.", "Ancak oylamayla serbest bırakılır."],
  "chest.unlabelled": ["{amt} USDC arrived without a label: the agent or a vote assigns it.", "{amt} USDC etiketsiz geldi: ajan ya da oylama bir üyeye yazar."],
  "chest.who": ["who brought the money in, this period", "bu dönem parayı kim getirdi"],
  "chest.shares": ["Shares by contribution", "Katkıya göre paylar"],
  "chest.noCredit": ["Nothing earned yet this period. Pin an invoice and send the pay link.", "Bu dönem henüz kazanç yok. Bir fatura iğnele ve ödeme bağlantısını gönder."],
  "chest.collect": ["Collect {amt} USDC", "{amt} USDC'yi al"],
  "chest.record": ["on the record · Arc", "kayıtta · Arc"],
  "chest.quiet": ["Quiet so far.", "Şimdilik sessiz."],
  "chest.notAddress": ["That isn't a chest address.", "Bu bir kasa adresi değil."],
  "chest.readFail": ["Couldn't read this chest from Arc. Is the address right?", "Bu kasa Arc'tan okunamadı. Adres doğru mu?"],
  "chest.back": ["Back to the board", "Panoya dön"],
  "tx.payOut": ["Pay out", "Dağıtım"],
  "tx.collect": ["Collect payout", "Payı alma"],
  "ev.opened": ["Chest opened", "Kasa açıldı"],
  "ev.invoiceCreated": ["Invoice pinned · {amt} USDC", "Fatura iğnelendi · {amt} USDC"],
  "ev.invoicePaid": ["Invoice paid · {amt} USDC ({res} to reserve)", "Fatura ödendi · {amt} USDC ({res} yedeğe)"],
  "ev.invoiceCancelled": ["Invoice cancelled", "Fatura iptal edildi"],
  "ev.settled": ["Agent matched {amt} USDC from another chain to an invoice", "Ajan başka zincirden gelen {amt} USDC'yi faturaya eşledi"],
  "ev.paid": ["Paid out {amt} USDC → {who}", "{amt} USDC dağıtıldı → {who}"],
  "ev.deferred": ["Payout held for {who} · {amt} USDC (collect anytime)", "{who} için pay bekletiliyor · {amt} USDC (istediği zaman alır)"],
  "ev.distributed": ["Period #{n} closed · {amt} USDC shared", "#{n} dönemi kapandı · {amt} USDC paylaşıldı"],
  "ev.attributed": ["Agent credited {amt} USDC → {who}", "Ajan {amt} USDC'yi yazdı → {who}"],
  "ev.expense": ["Bill paid · {amt} USDC → {who}", "Fatura ödendi · {amt} USDC → {who}"],
  "ev.proposed": ["Vote #{n} opened", "#{n} oylaması açıldı"],
  "ev.executed": ["Vote #{n} carried out", "#{n} oylaması uygulandı"],
  "ev.reserve": ["Reserve released · {amt} USDC → {who}", "Yedek serbest bırakıldı · {amt} USDC → {who}"],
  "ev.claimed": ["Collected {amt} USDC", "{amt} USDC alındı"],

  // invoices
  "inv.label": ["invoices", "faturalar"],
  "inv.title": ["Work pinned to money", "Paraya iğnelenmiş iş"],
  "inv.new": ["+ New invoice", "+ Yeni fatura"],
  "inv.close": ["Close", "Kapat"],
  "inv.none": ["No invoices yet.", "Henüz fatura yok."],
  "inv.payLink": ["pay link ↗", "ödeme bağlantısı ↗"],
  "inv.status.1": ["open", "açık"],
  "inv.status.2": ["paid", "ödendi"],
  "inv.status.3": ["cancelled", "iptal"],
  "inv.amount": ["amount (USDC)", "tutar (USDC)"],
  "inv.payer": ["who pays (optional)", "kim ödeyecek (isteğe bağlı)"],
  "inv.anyone": ["anyone", "herkes"],
  "inv.who": ["who did the work, and their share — fixed before the money arrives", "işi kim yaptı ve payı ne — para gelmeden önce sabitlenir"],
  "inv.addPerson": ["+ Add person", "+ Kişi ekle"],
  "inv.pin": ["Pin invoice", "Faturayı iğnele"],
  "inv.pinning": ["Pinning…", "İğneleniyor…"],
  "inv.err.amount": ["Enter an amount.", "Bir tutar gir."],
  "inv.err.payer": ["Payer must be an address or empty (anyone can pay).", "Ödeyen bir adres olmalı ya da boş kalmalı (herkes ödeyebilir)."],
  "inv.err.total": ["Shares add up to {n}%, need 100%.", "Paylar toplamı %{n}, %100 olmalı."],
  "inv.err.dup": ["A member is listed twice.", "Bir üye iki kez yazılmış."],
  "tx.createInvoice": ["Create invoice", "Fatura oluşturma"],

  // votes
  "vote.label": ["votes", "oylamalar"],
  "vote.title": ["Nobody moves money alone", "Kimse parayı tek başına oynatamaz"],
  "vote.hint": ["More than half of members must agree, then a {d} wait.", "Üyelerin yarısından fazlası onaylamalı, sonra {d} beklenir."],
  "vote.none": ["Nothing on the ballot.", "Oylamada bir şey yok."],
  "vote.canRun": ["can run in {d}", "{d} sonra uygulanabilir"],
  "vote.openFor": ["open for {d}", "{d} daha açık"],
  "vote.by": ["by {who}", "açan: {who}"],
  "vote.yes": ["Vote yes", "Evet oyu ver"],
  "vote.takeBack": ["Take back my vote", "Oyumu geri al"],
  "vote.carry": ["Carry it out", "Uygula"],
  "vote.withdraw": ["Withdraw", "Geri çek"],
  "vote.past": ["past votes", "geçmiş oylamalar"],
  "vote.carried": ["carried out", "uygulandı"],
  "vote.withdrawn": ["withdrawn", "geri çekildi"],
  "vote.lapsed": ["lapsed", "süresi doldu"],
  "vote.open": ["open a vote", "oylama aç"],
  "vote.k.AddMember": ["Add a member", "Üye ekle"],
  "vote.k.RemoveMember": ["Remove a member", "Üye çıkar"],
  "vote.k.SetAgent": ["Set the agent", "Ajanı belirle"],
  "vote.k.SetPayee": ["Allow a bill recipient", "Fatura alıcısına izin ver"],
  "vote.k.ReleaseReserve": ["Release reserve to members (equal split)", "Yedeği üyelere serbest bırak (eşit böl)"],
  "vote.k.SetRules": ["Change reserve share", "Yedek payını değiştir"],
  "vote.submit": ["Put it to a vote", "Oylamaya sun"],
  "vote.err.addr": ["Enter a wallet address.", "Bir cüzdan adresi gir."],
  "vote.err.payee": ["Enter the address bills go to.", "Faturaların gideceği adresi gir."],
  "vote.err.amount": ["Enter an amount.", "Bir tutar gir."],
  "vote.err.reserveMax": ["Reserve holds {amt} USDC.", "Yedekte {amt} USDC var."],
  "vote.err.pct": ["Reserve share must be 0–100%.", "Yedek payı %0–100 olmalı."],
  "vote.err.check": ["Check the values.", "Değerleri kontrol et."],
  "vote.upTo": ["up to {amt} USDC", "en fazla {amt} USDC"],
  "vote.pctPh": ["reserve %", "yedek %"],
  "vote.d.add": ["Add {who} as a member", "{who} üye olsun"],
  "vote.d.remove": ["Remove {who}", "{who} çıkarılsın"],
  "vote.d.noAgent": ["Remove the agent", "Ajan kaldırılsın"],
  "vote.d.agent": ["Make {who} the agent", "{who} ajan olsun"],
  "vote.d.payee": ["Allow bills to {who}", "{who} adresine fatura ödenebilsin"],
  "vote.d.noPayee": ["Stop bills to {who}", "{who} adresine fatura ödenmesin"],
  "vote.d.release": ["Release {amt} USDC of reserve to {who}", "Yedekten {amt} USDC serbest bırakılsın → {who}"],
  "vote.d.attribute": ["Credit {amt} USDC of unlabelled income to {who}", "Etiketsiz {amt} USDC {who} adına yazılsın"],
  "vote.d.expense": ["Pay {amt} USDC to {who}", "{who} adresine {amt} USDC ödensin"],
  "vote.d.rules": ["New rules: reserve {pct} up to {amt}, pay out every {d}", "Yeni kurallar: yedek {pct}, {amt}'ye kadar; her {d} dağıtım"],
  "vote.d.settle": ["Mark invoice {id} paid from money that arrived without a reference", "{id} faturası, referanssız gelen parayla ödenmiş sayılsın"],
  "tx.vote": ["Vote", "Oy"],
  "tx.unvote": ["Take back vote", "Oy geri alma"],
  "tx.execute": ["Carry out", "Uygulama"],
  "tx.cancel": ["Withdraw", "Geri çekme"],
  "tx.propose": ["Open vote", "Oylama açma"],

  // pay
  "pay.broken": ["This pay link is broken.", "Bu ödeme bağlantısı bozuk."],
  "pay.missing": ["There's no invoice behind this link.", "Bu bağlantının arkasında bir fatura yok."],
  "pay.from": ["invoice from", "fatura sahibi"],
  "pay.onArc": ["USDC on Arc", "USDC · Arc"],
  "pay.who": ["who did the work", "işi kim yaptı"],
  "pay.explain": [
    "Your payment lands in the team's chest on Arc. A reserve is set aside first, the rest is shared by these percentages at the end of the period.",
    "Ödemen ekibin Arc'taki kasasına düşer. Önce yedek ayrılır, kalanı dönem sonunda bu yüzdelere göre paylaşılır.",
  ],
  "pay.label": ["pay", "öde"],
  "pay.step1": ["Allow exactly {amt} USDC", "Tam {amt} USDC'ye izin ver"],
  "pay.step2": ["Pay — the invoice reference is recorded on Arc", "Öde — fatura numarası Arc'a kaydedilir"],
  "pay.have": ["You have {amt} USDC on Arc.", "Arc'ta {amt} USDC'n var."],
  "pay.wrongPayer": ["This invoice is addressed to {who}.", "Bu fatura {who} adresine kesilmiş."],
  "pay.short": ["Not enough USDC on Arc for this invoice.", "Bu fatura için Arc'ta yeterli USDC yok."],
  "pay.allow": ["1 · Allow {amt} USDC", "1 · {amt} USDC'ye izin ver"],
  "pay.pay": ["2 · Pay {amt} USDC", "2 · {amt} USDC öde"],
  "pay.thanks": ["Thank you. The team's chest has it.", "Teşekkürler. Para ekibin kasasında."],
  "pay.see": ["see it on Arc ↗", "Arc'ta gör ↗"],
  "pay.cancelled": ["This invoice was cancelled by the team.", "Bu fatura ekip tarafından iptal edildi."],
  "pay.lookInside": ["Look inside this chest →", "Bu kasanın içine bak →"],
  "tx.allow": ["Allow payment", "Ödeme izni"],
  "tx.payInvoice": ["Pay invoice", "Fatura ödeme"],

  // toast + errors
  "toast.pending": ["on its way", "yolda"],
  "toast.ok": ["done", "tamam"],
  "toast.error": ["didn't go through", "gerçekleşmedi"],
  "toast.confirm": ["{label}: confirm in your wallet…", "{label}: cüzdanında onayla…"],
  "toast.waiting": ["{label}: waiting for Arc…", "{label}: Arc bekleniyor…"],
  "toast.done": ["{label}: done.", "{label}: tamamlandı."],
  "toast.view": ["view on Arc explorer ↗", "Arc explorer'da gör ↗"],
  "err.rejected": ["You cancelled it in the wallet.", "Cüzdanda iptal ettin."],
  "err.reverted": ["Transaction reverted on Arc.", "İşlem Arc'ta geri döndü."],
  "err.NotAMember": ["That address isn't a member of this chest.", "Bu adres kasanın üyesi değil."],
  "err.NotMemberOrAgent": ["Only members can do this.", "Bunu yalnızca üyeler yapabilir."],
  "err.BadShares": ["Shares must add up to 100%.", "Paylar toplamı %100 olmalı."],
  "err.BadRules": ["Those rules aren't allowed: more than half must vote and the wait must be at least 1 hour.", "Bu kurallara izin yok: yarıdan fazlası oy vermeli ve bekleme en az 1 saat olmalı."],
  "err.InvoiceNotOpen": ["This invoice is already paid or cancelled.", "Bu fatura zaten ödenmiş ya da iptal edilmiş."],
  "err.WrongPayer": ["This invoice is addressed to a different payer.", "Bu fatura başka bir ödeyene kesilmiş."],
  "err.AmountMismatch": ["The invoice amount changed. Reload and try again.", "Fatura tutarı değişmiş. Sayfayı yenileyip tekrar dene."],
  "err.PeriodNotOver": ["The period isn't over yet.", "Dönem henüz bitmedi."],
  "err.NoQuorum": ["Not enough votes yet.", "Henüz yeterli oy yok."],
  "err.TimelockActive": ["Still in the waiting time.", "Bekleme süresi devam ediyor."],
  "err.ProposalExpired": ["This vote expired.", "Bu oylamanın süresi doldu."],
  "err.ProposalStale": ["Members or rules changed since this vote opened; open a new one.", "Bu oylama açıldıktan sonra üyeler ya da kurallar değişti; yenisini aç."],
  "err.AlreadyVoted": ["You already voted on this.", "Buna zaten oy verdin."],
  "err.AboveCap": ["Above the limit; it needs a vote.", "Sınırın üstünde; oylama gerekiyor."],
  "err.InsufficientPool": ["Not enough in this period's pot.", "Bu dönem birikende yeterli para yok."],
  "err.InsufficientReserve": ["Not enough in the reserve.", "Yedekte yeterli para yok."],

  // reachability
  "net.down": ["Can't reach Arc right now.", "Şu an Arc'a ulaşılamıyor."],
  "net.downBody": ["The network didn't answer. Your funds are safe on chain; try again in a moment.", "Ağ cevap vermedi. Paran zincirde güvende; birazdan tekrar dene."],
  "net.retry": ["Try again", "Tekrar dene"],

  // time
  "time.now": ["now", "şimdi"],
  "time.d": ["d", "g"],
  "time.h": ["h", "sa"],
  "time.m": ["m", "dk"],
});
