import { defineStrings } from "../lib/i18n";

defineStrings({
  "ag.label": ["the agent", "ajan"],
  "ag.title": ["Runs the chest inside the rules", "Kasayı kuralların içinde yürütür"],
  "ag.model": ["model", "model"],
  "ag.address": ["agent wallet", "ajan cüzdanı"],
  "ag.connected": ["connected to this chest", "bu kasaya bağlı"],
  "ag.notConnected": ["Not connected to this chest yet. Members vote it in.", "Henüz bu kasaya bağlı değil. Üyeler oylamayla bağlar."],
  "ag.connectVote": ["Open a vote to connect the agent", "Ajanı bağlamak için oylama aç"],
  "ag.unreachable": ["The agent service didn't answer. The chest works without it; votes and payouts are on chain.", "Ajan servisi cevap vermedi. Kasa onsuz da çalışır; oylama ve dağıtım zincirde."],
  "ag.empty": ["No decisions yet. Invoices sent to the chest's mailbox and money arriving from other chains show up here.", "Henüz karar yok. Kasanın e-posta adresine gelen faturalar ve başka zincirlerden gelen paralar burada görünür."],
  "ag.decisions": ["what the agent decided", "ajan neye karar verdi"],
  "ag.facts": ["facts from the chain and the document", "zincir ve belgedeki gerçekler"],
  "ag.checks": ["checks", "kontroller"],
  "ag.reasoning": ["the agent's reading — compare it with the facts", "ajanın yorumu — gerçeklerle karşılaştır"],
  "ag.ref": ["sealed as", "mühür"],
  "ag.tx": ["transaction ↗", "işlem ↗"],
  "ag.o.paid": ["paid", "ödendi"],
  "ag.o.settled": ["matched", "eşlendi"],
  "ag.o.vote": ["sent to a vote", "oylamaya gitti"],
  "ag.o.held": ["held", "bekletildi"],
  "ag.o.rejected": ["refused", "reddedildi"],
  "ag.o.noted": ["note", "not"],
  "ag.o.distributed": ["paid out", "dağıtıldı"],
  "ag.stamp.refused": ["REFUSED", "REDDEDİLDİ"],
  "ag.note": ["this week's treasury note", "bu haftanın hazine notu"],
  "ag.suggest": ["Suggests a {pct}% reserve share", "Yedek payını %{pct} yapmayı öneriyor"],
  "ag.suggestVote": ["Put it to a vote", "Oylamaya aç"],
  "ag.settings": ["agent settings (members)", "ajan ayarları (üyeler)"],
  "ag.vendors": ["suppliers the agent may pay", "ajanın ödeyebileceği tedarikçiler"],
  "ag.vendorsHint": ["The agent pays only these, only to the address you register here, and only if the chest allowlisted it by vote.", "Ajan yalnızca bunlara, yalnızca burada kayıtlı adrese ve yalnızca kasa oylamayla izin verdiyse öder."],
  "ag.v.name": ["name", "isim"],
  "ag.v.domain": ["email domain", "e-posta alan adı"],
  "ag.v.payTo": ["pays to", "ödeme adresi"],
  "ag.v.typical": ["usual (USDC)", "olağan (USDC)"],
  "ag.v.max": ["max (USDC)", "üst sınır (USDC)"],
  "ag.v.add": ["+ Add supplier", "+ Tedarikçi ekle"],
  "ag.v.remove": ["Remove", "Çıkar"],
  "ag.v.save": ["Save (sign)", "Kaydet (imzala)"],
  "ag.v.saved": ["Saved.", "Kaydedildi."],
  "ag.v.allowed": ["allowlisted", "izinli"],
  "ag.v.notAllowed": ["not allowlisted", "izinli değil"],
  "ag.v.allowVote": ["Open allowlist vote", "İzin için oylama aç"],
  "ag.v.invalid": ["Check every row: a name, a domain, a 0x address and amounts.", "Her satırı kontrol et: isim, alan adı, 0x adres ve tutarlar."],
  "ag.inbox": ["invoice mailbox", "fatura e-postası"],
  "ag.inboxHint": ["Forward supplier invoices here; the agent reads them.", "Tedarikçi faturalarını buraya yönlendir; ajan okur."],
  "ag.inboxSave": ["Connect (sign)", "Bağla (imzala)"],
  "ag.run": ["Run the agent now", "Ajanı şimdi çalıştır"],
  "ag.running": ["Running…", "Çalışıyor…"],
  "ag.done": ["Done.", "Tamam."],
  "tx.agentVote": ["Open vote", "Oylama açma"],
});
