import { defineStrings } from "../lib/i18n";

/** Every user-facing landing string, English + Turkish. */
export const L = defineStrings({
  "l.tagline": ["the guild chest, onchain", "loncanın ortak kasası, zincirde"],
  "l.nav.why": ["Why", "Neden"],
  "l.nav.how": ["How", "Nasıl"],
  "l.nav.rules": ["Rules", "Kurallar"],
  "l.nav.open": ["Open the app", "Uygulamayı aç"],

  "l.hero.eyebrow": ["For teams that earn together", "Birlikte kazanan ekipler için"],
  "l.hero.l1": ["Earn together.", "Birlikte kazan."],
  "l.hero.l2": ["Split by", "Emeğe göre"],
  "l.hero.l3": ["the work.", "bölüş."],
  "l.hero.lede": [
    "A shared chest on Arc. Every payment is pinned to the job that earned it, a reserve goes aside first, and the rest is paid out by what each person actually did.",
    "Arc üzerinde ortak bir kasa. Her ödeme onu kazandıran işe iğnelenir, önce yedek ayrılır, kalanı herkesin gerçekten yaptığı işe göre dağıtılır.",
  ],
  "l.hero.start": ["Start a chest", "Kasa aç"],
  "l.hero.see": ["See the board move", "Panoyu izle"],
  "l.role.frontend": ["frontend", "ön yüz"],
  "l.role.design": ["design", "tasarım"],
  "l.role.contracts": ["contracts", "kontratlar"],
  "l.job.berlin": ["Job · Berlin client", "İş · Berlin'deki müşteri"],
  "l.job.web": ["Website, phase 2", "Web sitesi, 2. aşama"],
  "l.job.agents": ["Sold to agents · x402", "Ajanlara satıldı · x402"],
  "l.job.api": ["Invoice parser API", "Fatura okuma API'si"],

  "l.but.note1": ["“Who decided I get 40%?”", "“%40'ı bana kim uygun gördü?”"],
  "l.but.note2": ["Berlin client can't pay. No PayPal here. Wire is $45.", "Berlin'deki müşteri ödeyemiyor. Burada PayPal yok. Havale 45 dolar."],
  "l.but.note3": ["Ran out of cash in August. Nothing set aside.", "Ağustosta nakit bitti. Kenara hiçbir şey ayrılmamıştı."],
  "l.sheet.file": ["split_FINAL_v7(2).xlsx", "paylasim_SON_v7(2).xlsx"],
  "l.sheet.edited": ["edited by Ali · 02:14", "Ali düzenledi · 02:14"],
  "l.sheet.web": ["web p2", "web 2. aş."],
  "l.sheet.check": ["?? check", "?? bak"],
  "l.sheet.reserve": ["reserve", "yedek"],
  "l.sheet.forgot": ["forgot", "unutuldu"],
  "l.but.title.a": ["But the split lives in ", "Ama bölüşüm "],
  "l.but.title.em": ["one person's", "tek bir kişinin"],
  "l.but.title.b": [" spreadsheet.", " Excel'inde duruyor."],

  "l.so.title": ["So the chest does the splitting.", "Bu yüzden bölüşümü kasa yapıyor."],
  "l.so.invoice": ["Invoice #014 · paid from Base", "Fatura #014 · Base'den ödendi"],
  "l.so.client": ["Berlin client", "Berlin'deki müşteri"],
  "l.so.amount": ["2,000 USDC", "2.000 USDC"],
  "l.rules.senderAmt": ["5,000 USDC", "5.000 USDC"],
  "l.so.matched": ["Matched to", "Eşleştiği iş"],
  "l.so.reserve": ["Reserve · first", "Yedek · önce"],
  "l.so.step1": ["Money arrives, any chain", "Para gelir, hangi zincirden olursa"],
  "l.so.step2": ["Pinned to the job that earned it", "Onu kazandıran işe iğnelenir"],
  "l.so.step3": ["Reserve goes aside first", "Önce yedek ayrılır"],
  "l.so.step4": ["The rest, split by the work", "Kalanı emeğe göre bölünür"],
  "l.so.period": ["Period 10 · October", "10. dönem · Ekim"],
  "l.so.day": ["day 02 · ", "2. gün · "],
  "l.so.flag1.n": ["+2,000", "+2.000"],
  "l.so.flag1": [" paid from Base", " Base'den ödendi"],
  "l.so.flag2": [" to reserve", " yedeğe"],
  "l.so.flag3.n": ["1,800", "1.800"],
  "l.so.flag3": [" split 60 / 40", " 60 / 40 bölündü"],

  "l.rules.title": ["Rules change by vote. The agent works inside them.", "Kurallar oyla değişir. Ajan o kuralların içinde çalışır."],
  "l.rules.proposal": ["Proposal 07 · needs 4 of 6", "Öneri 07 · 6 oydan 4'ü gerekli"],
  "l.rules.reserve3": ["Keep three months of costs in reserve", "Üç aylık gideri yedekte tut"],
  "l.rules.yes": ["YES", "EVET"],
  "l.rules.unknown": ["Unknown sender", "Tanınmayan gönderen"],
  "l.rules.agent": ["Agent · 03:12", "Ajan · 03:12"],
  "l.rules.agentNote": [
    "5,000 USDC arrived from a sender I don't know. Above my limit, so I'm holding it. Want me to pin it to a job?",
    "Tanımadığım bir göndericiden 5.000 USDC geldi. Limitimin üstünde, o yüzden bekletiyorum. Bir işe iğneleyeyim mi?",
  ],
  "l.rules.held": ["HELD", "BEKLEMEDE"],
  "l.rules.ruler": ["Agent can move per period", "Ajanın dönem başına yetkisi"],
  "l.rules.limit": ["limit 1,500 USDC · set by vote", "limit 1.500 USDC · oyla belirlendi"],
  "l.rules.log1": ["03:12  held 5,000 USDC · unknown sender → asked members", "03:12  5.000 USDC bekletildi · tanınmayan gönderen → üyelere soruldu"],
  "l.rules.log2": ["03:14  paid hosting 42 USDC · allowlisted · inside limit", "03:14  sunucu faturası 42 USDC ödendi · onaylı alıcı · limit içinde"],
  "l.rules.log3": ["03:20  proposal 07 passed 4/6 · reserve = 3 months", "03:20  öneri 07 kabul edildi 4/6 · yedek = 3 ay"],

  "l.close.period": ["Period 11", "11. dönem"],
  "l.close.opens": ["opens today", "bugün açılıyor"],
  "l.close.label": ["Month end · everyone paid · board cleared", "Ay sonu · herkese ödendi · pano temizlendi"],
  "l.close.title": ["Pin your first job.", "İlk işini iğnele."],
  "l.close.body": [
    "Set the reserve, add the people, send the first payment link. The chest keeps the count from there.",
    "Yedeği belirle, ekibi ekle, ilk ödeme bağlantısını gönder. Gerisinin hesabını kasa tutar.",
  ],
  "l.close.contract": ["Read the contract", "Kontratı incele"],
  "l.foot.a": ["Built on Arc · settled in USDC", "Arc üzerinde · USDC ile ödenir"],
  "l.foot.b": ["Keyarc · live on Arc mainnet", "Keyarc · Arc mainnet'te canlı"],
});
